version: "3.3"

# Define services
services:
  # App backend service  
  back-blog:
    container_name: back-blog
    image: haniel/back-blog
    # Configuration for building the docker image for the backend service
    build:
      context: . # Use an image built from the specified dockerfile in the `backend` directory.
      dockerfile: Dockerfile
    ports:
      - "4000:4000" # Forward the exposed port 4000 on the container to port 4000 on the host machine
    restart: always
    depends_on: 
      - mongodb # This service depends on mongodb. Start that first.
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backendnet
      - frontendnet

  # Database Service (Mongodb)
  mongodb:
    container_name: mongodb
    image: tutum/mongodb
    ports:
      - "27017:27017"
    restart: always
    environment:
      - AUTH=no
    volumes:
      - /data/db:/data/db
    networks:
      - backendnet

# Networks to be created to facilitate communication between containers
networks:
  backendnet:
  frontendnet:    